### ISSUE TITLE
Prepared statements / debugging query performance?

### ISSUE THREAD

**Issue by rattrayalex** [graphile/persisted-operations#6]
Heya,

I'm considering postgraphile for a project, and one of my core anxieties about the tool (and graphql in general) is being able to detect and diagnose huge, expensive queries. Persisted operations seems like one helpful way to at least lock that down to known-at-build-time queries, but the next step would be to actually understand the performance of these queries. 

One approach might be [prepared statements](https://www.postgresql.org/docs/current/sql-prepare.html) – saving each persisted operation as its sha. This would reduce query parsing and planning time, which I assume isn't much.

My thinking is that this might also help make it easier to see what queries are running frequently and expensively, debug their query plans, etc – but this may be totally off-base.

As an aside, it might be worth adding a section to [Production Considerations](https://www.graphile.org/postgraphile/production/) talking about how to understand your query performance.

Cheers!

**Comment by benjie** [comment]
Have you tried the `EXPLAIN` functionality in our enhanced GraphiQL? It's generally pretty useful for figuring out where you've missed an index. I also wrote https://pgrita.com to help detect these kinds of issues in Postgres in general.

> Persisted operations seems like one helpful way to at least lock that down to known-at-build-time queries

Persisted operations themselves are not sufficient to lock down an SQL query (unless done very carefully); for example take the following persisted operation:

```graphql
query Q ($condition: UsersCondition) {
  allUsersList(condition: $condition) { id }
}
```

Depending on what values you pass as the `$condition` variable, different SQL will be generated (different `WHERE` clauses).

> One approach might be prepared statements – saving each persisted operation as its sha. This would reduce query parsing and planning time, which I assume isn't much.

We already use prepared statements automatically via the `pgPrepareAndRun` helper: https://github.com/graphile/graphile-engine/blob/1bc8cfefdab7a61fd7ad287bcdff66298352e308/packages/graphile-build-pg/src/pgPrepareAndRun.js#L23

>  talking about how to understand your query performance.

Indeed, I normally think this is a job for the PostgreSQL docs/tools but you're right that it may be valuable to link to the relevant places and also to talk about how different GraphQL shapes can affect performance.

**Comment by rattrayalex** [comment]
Heh, sounds like there's a lot of awesome undocumented stuff at play! Or perhaps just hard to find, spent the last few days reading the docs and was not aware of:

1. `EXPLAIN` functionality built in to the enhanced GraphiQL. It may have been mentioned offhand but a screenshot or even guide would have been helpful.
2. The existence of `pgRITA`. Surprised this isn't mentioned in the "Advanced" section of Performance Considerations, but it looks awesome.
3. That graphile uses prepared statements automatically (cool!) or that it has a default limit of 100 (eek, minor undocumented performance cliff).

Anyway, I guess this boils into a few feature requests:

### Performance Debugging Guide

I think before I operate a tool I like to have an idea of how I'll keep an eye on its performance, and how I'll monitor & improve it. Postgraphile is fairly unique in that it generates a single SQL statement for each (potentially very large/complex) graphql query, and of course graphql compared to rest means you only have "one endpoint" so you can't monitor and diagnose per-endpoint performance over time.

If I log into postgres and look for the most expensive queries, how will I map those back to graphql queries? How easy will it be to tell where those graphql queries are coming from? How easy will it be able to tell what part of the (potentially very large) query is slow?

I'm nervous about adopting/recommending a tool where I don't have much idea as to the answer to these questions, and a guide with screenshots / code snippets might be helpful there – the good news is it sounds like many of the puzzle pieces are there.

I'm guessing this has been on your to-do for some time, and won't happen till some time after v5, which is understandable.

### Use persisted operation sha's for prepared statement sha's

As I hinted above, it'd be nice to be able to look at running queries in postgres and map that back to graphql queries in my application, so I can diagnose and improve my gql query performance in a potentially large application. Maybe there's already a good workflow for this?

Of course, this would break unless you also…

### Prevent persisted operation from generating polymorphic SQL queries

I think the scenario you outlined above is one I would probably like to prevent, or at least have to whitelist:

>  `query Q ($condition: UsersCondition) { allUsersList(condition: $condition) { id } }`
> Depending on what values you pass as the `$condition` variable, different SQL will be generated (different `WHERE` clauses).

I'm not sure how best to accomplish this – probably a runtime error if the generated sql does not match the expected? I assume a build-time operation would not be possible to build reliably.

This may also not be a restriction anyone would want in practice, I'm not sure – but I'd feel nervous using a tool like `postgraphile-plugin-connection-filter` without this, and I'm not sure I'd want to use `postgraphile` without the convenience of `connection-filter`!

What do you think? Would you like me to break these out into separate issues? Are they no-gos?

**Comment by benjie** [comment]
> EXPLAIN functionality built in to the enhanced GraphiQL. It may have been mentioned offhand but a screenshot or even guide would have been helpful.

Is this enhanced GraphiQL itself that you didn't notice, or the explain button at the top? We do put it into the "recommended options" at the top of the usage documentation:

https://www.graphile.org/postgraphile/usage-cli/#for-development

Changing these defaults (so that these are automatically enabled) is not something we can do in a minor version, which is why I'm introducing the concept of presets to V5 so that I can change the defaults over time by just introducing a newer preset and advising its use.

> pgRITA

Still a work in progress; still factoring in feedback from the existing users to make it better before we go after a wider audience.

> I think the scenario you outlined above is one I would probably like to prevent, or at least have to whitelist:

There's _so many_ different things that could cause this, and many that we have no way of protecting against - for example third party plugins that change behaviour based on a boolean field. It's just not tenable to have something as powerful as PostGraphile apply these limits automatically. You can apply them to your own stack, potentially, by being very careful in the queries you build; e.g. never using `@skip` / `@include` directives, never passing different values for conditions or orders, never using makeWrapResolversPlugin to take secondary actions based on inputs, etc.

> That graphile uses prepared statements automatically (cool!) or that it has a default limit of 100 (eek, minor undocumented performance cliff).

Personally I'd assume that a system like PostGraphile that leverages the internal powers of database so heavily would know about and utilise persisted queries, so I didn't think it warranted documentation. It's just an implementation detail, a minor optimisation in certain circumstances. I also didn't notice sufficient speedup that I would expect a "performance cliff" when they cannot be utilised, so again, I didn't feel it warranted documentation. If you fancy doing some benchmarking and finding out how deep this cliff is when you pass it, I'd love to see it, and we could add the details to the performance page. Since prepared statements consume memory on the server, we must limit the number that are used; 100 seems a fair LRU size for the kinds of hot queries I see in PostGraphile instances.

> Performance Debugging Guide

This would indeed be valuable, but I'm currently focussed on V5 which would invalidate a lot of the assumptions in such a document, so writing it now would delay V5 and have a very limited lifespan.

I suggest you benchmark your workloads; that ultimately will give a much better idea of how your system will scale than words on a page.

**Comment by rattrayalex** [comment]
Explain in GraphiQL: I didn't read the CLI guide since I don't plan on using the CLI to run the application. I was aware there was an enhanced GraphiQL, but I didn't know it had EXPLAIN functionality – but it turns out [this is indeed documented](https://www.graphile.org/postgraphile/debugging/#via-postgraphiql-explain)! I had somehow missed the "Debugging" docs 😅 which addresses many of my wishes.

Re; pgRita, makes sense, good luck! 

Re; preventing polymorphic queries: Having worked on large teams, I don't really believe in "be very careful not to do X" – if it can't be prevented at build time (eg by raising errors or linting) it will happen. To be clear, I didn't mean that postgraphile should automatically block this kind of thing by default, just that perhaps there should be an option or plugin to do so, but it's probably best for that to just be a custom plugin anyway – I think it should be achievable. 

The concept is probably misguided in any case – minor polymorphism like `@skip` or `@include` is probably more helpful than not. A cost estimator like [this](https://github.com/pa-bru/graphql-cost-analysis) and/or the experimental one in graphile pro, combined with well-chosen statement timeout. 

I suppose one could make a `statement-budget` graphile plugin, in which you annotate gql queries on the client with, eg, `@budget(1000)` which would be summed on the backend and used for a dynamic `set local statement_timeout`? Thus limiting DDoS risk, allowing a ratchet for query performance, and generally bringing perf visibility to the frontend?

Re; documenting prepared statements, fair enough!

**Comment by benjie** [comment]
The client controlled budget combined with persisted operations is an interesting one! I typically trust persisted operations to already be within budget, but this definitely doesn’t scale to larger teams. I’d love to see a plugin implementing this 👍

**Comment by rattrayalex** [comment]
Cool, thanks for the encouragement!

I opened up https://github.com/graphile/graphile-engine/issues/731 to keep track of the idea since I have no immediate plans to build it. 

(To be quite honest, thinking about looking at a super-massive generated sql query and trying to figure out why it's slow, when probably only one part of it is, is enough to send me off to slower-by-default but more-understandable/predictable systems like REST… maybe these fears are unfounded but I don't see examples of what a big page's graphql would look like in terms of graphile's sql and the associated query plan)

**Comment by benjie** [comment]
The queries look complex but they’re quite straightforward when you get used to them - they’re a pretty linear map of what you’re asking from GraphQL via a bunch of subqueries; and since they’re generally relational they mostly use indexes. They only get performance issues when you start adding unoptimised filtering/ordering to them, hence why I recommend defining your own custom filters/orders that you can optimise e.g. via makeAddPgTableConditionPlugin rather than using a generic plugin.

**Comment by rattrayalex** [comment]
Hmm... Could you post some examples of the generated SQL? Would probably be helpful to many people considering (or even using) postgraphile in any case. Would probably be super awesome to have the generated SQL below the gql in [the examples gallery](https://www.graphile.org/postgraphile/examples).

Frankly, I don't really buy that queries will be performant if only you declare them on the backend instead of the frontend. If you're trying to do an expensive query on something that isn't indexed, it's gonna be slow whether you write in with graphql or an ORM or sql*. The fix is (probably) to add the right index, which you should only do once you _know_ your query is actually slow (since indexes hurt writes).

A tool/workflow to get EXPLAIN information for each persisted query given expected example variables at build time – combined with tooling to, say, fail the build if the expected cost is too high – is something I would trust much, much more. (Actually, that sounds like a pretty good idea… EDIT: opened issue https://github.com/graphile/persisted-operations/issues/7 for discussion). 

Failing that, I'd still rather rely on good production alerting to notify the team of slow queries (and a culture of fixing it) than avoiding tools that just make it easy to write queries.

\* Some queries might even be slow _because_ you tried putting important parts of it into a view or function instead of letting it be raw generated sql! (I've heard [FUD](https://twitter.com/spakhm/status/1378146673281667074) about [view perf](https://twitter.com/RobertBMenke/status/1378158547926663168) anyway). It seems entirely possible that connection-filter would write better SQL than my team would, since they might get lazy.

**Comment by benjie** [comment]
> Could you post some examples of the generated SQL? 

SQL is seen as an implementation detail, we change the SQL that's generated from time to time (even in patch releases) so it's definitely not something that should be a documented interface.

You can see the SQL that PostGraphile generates:

Either: by using `postgraphile --enhance-graphiql --allow-explain` and:

  - Either using the `explain` functionality in GraphiQL, or
  - Setting the `x-postgraphile-explain: on` header on your GraphQL requests (SQL and explain will be included in the response payload, as visible in GraphiQL)

Or: using the `DEBUG="postgraphile:postgres"` envvar, see the [Debugging](https://www.graphile.org/postgraphile/debugging/#via-debug-envvar) page.

**Comment by rattrayalex** [comment]
That sounds great once someone has decided to use postgraphile, but choosing it is a pretty big bet – when someone is in the evaluation stage of a technology, it's really nice to be able to get a good feel for what it'll be like to use and operate without having to download and run anything.

Since that's the stage I'm in, I'd have to find a reasonably complex example database somewhere on the internet, download it, run postgraphile from the command line with several flags (I can probably copy a sizable from the docs which is merciful), and then come up with a variety of queries myself to see what things look like.

Failing docs, it might be helpful to have a live demo of a relatively rich/representative db/app showing off many of the features, so prospective users can get a feel for what's happening under the hood without friction.

I do kinda get the impression you're not very interested in finding new users for the project until v5, which I guess I can understand, so maybe this is worth thinking about then... as it stands, npmtrends over the last year doesn't tell a story of growth. When you're ready to focus on increasing adoption I'd really love to help.

**Comment by benjie** [comment]
> That sounds great once someone has decided to use postgraphile, but choosing it is a pretty big bet – when someone is in the evaluation stage of a technology, it's really nice to be able to get a good feel for what it'll be like to use and operate without having to download and run anything.

We've deliberately made it incredibly simple to trial; it's just one command if you have Node installed: `npx postgraphile -c my_db_here` - I don't think running that one command is really a big bet. I personally feel optimising for making it easy for people to try/experience is better than optimising for explaining that experience through prose.

> Failing docs, it might be helpful to have a live demo of a relatively rich/representative db/app showing off many of the features, so prospective users can get a feel for what's happening under the hood without friction.

Yes; this is my intent for Graphile Starter ultimately: 

https://graphile-starter.herokuapp.com/graphiql

But really, knowing how it works for some demo app that was carefully design, and knowing how it works for _your businesses database_ are two different things. I encourage you to try it with your own data.

> I do kinda get the impression you're not very interested in finding new users for the project until v5, which I guess I can understand, so maybe this is worth thinking about then... as it stands, npmtrends over the last year doesn't tell a story of growth. When you're ready to focus on increasing adoption I'd really love to help.

That's relatively accurate; time spent pushing v4 is time that's not spent building v5. I'm focussed on supporting the existing users of v4 and developing v5 - I see little point right now in detailing the inner workings of a system when I'm actively working on replacing those workings. I also think for the majority of users that the inner workings are an implementation detail in the same way that the memory structures V8 uses are not typically considered when evaluating whether Node.js solves your business problem. And for those who are really interested in seeing them (which are very few, in my experience) they can run a single command against their own database and concretely see what'll happen, rather than having to extrapolate from prose and demo applications.

**Comment by rattrayalex** [comment]
I understand.

I don't have a database yet, since I'm at the beginning of a project, so I can't try it out with my own data. The same would be true of anyone starting a new project and deciding between various application frameworks. 

Postgraphile seems quite "magical" compared to other ways of building an application, so I'd want to understand how it works before adopting it. I don't think of this as "inner workings" but merely "how it works". Perhaps you don't hear from many people for whom that's also true because they don't choose to use this tool (even if they should, because it does seem well-built). 

I just think a demo on the homepage saying it automatically turns "this gql into (roughly) this sql" would be an awesome selling point, that would help people much more quickly grok what postgraphile is, how it works, and why it's great. 

(If there's a little drift between _exactly_ what the docs say the sql is and what it really is, that's totally fine – I just want the general idea).

Leaning on graphile-starter to demo more of this, for example by linking to it prominently in the homepage and adding `--allow-explain`, would definitely also be great!

**Comment by rattrayalex** [comment]
I decided to fire this up with the standard [pagila](https://github.com/devrimgunduz/pagila) example db, using most of the command-line options in the "development" example from the docs.

[Here's the output for a couple queries](https://gist.github.com/rattrayalex/defcdffb3315348283757bd5f991beac).

I guess I definitely see what you're talking about with the sql being an implementation detail – all the json casts, `__local_3__` aliases, etc show that this wasn't _really_ intended for human consumption, and I can see how looking at it would unnecessarily turn people off. Even stuff like `and (TRUE) and (TRUE)` in the bottom of the query is obviously fine for getting the job done but not the most delicious for human consumption. I'm sure there's a lot you could "optimize away", and probably will at some point, but I wouldn't imagine it's a priority.

By the way, my understanding from the docs was that even something like this would execute a single sql statement, not two:
```sql
query MyQuery {
  actors() { ... }
  films() { ... }
}
```
I think two statements is better behavior, just FYI that I was confused by that. 

I gotta say, very impressive how quickly it fires up and executes, even if just on a toy db!!

**Comment by rattrayalex** [comment]
As a fun exercise, [I rewrote the generated sql for an example query](https://gist.github.com/rattrayalex/ae39c2cf0356f1257ece4f3c4f6488cd). I found the result quite beautiful – it really highlights how amazing postgraphile is. (EDIT: [opened an issue](https://github.com/graphile/graphile-engine/issues/734) to request moving to this for v5)

Personally I think it'd be quite fine to put up an altered example like this on the webpage with a headline like "Turn gql like this into sql (loosely) like this:"

(If anyone is following along at home, note that I renamed the `filmActors` on a film to `actors` with `comment on constraint film_actor_film_id_fkey on film_actor is E'@foreignFieldName actors';`)

Having played around with postgraphile like this, I have to say I am much more keen to use it!

**Comment by benjie** [comment]
What I really want to do is build a PostGraphile playground; I’ve been wanting to do that for so long but just haven’t had time. I need something like db-fiddle’s setup for databases and then maybe some on-demand node servers. Would be amazing for bug reports too: reproduce it on playground and it’s likely to get fixed faster! Would help with drafting plugins and all sorts. But of course running untrusted code is always a challenge, so I’ve not figured out the best way to accomplish it yet.

**Comment by rattrayalex** [comment]
Yeah, that sounds like quite an investment! Would be handy for sure though, especially for people who are already using postgraphile. 

Maybe a ["Deploy to Heroku" button](https://devcenter.heroku.com/articles/heroku-button) on a minimal "graphile-playground" repo that exposes both graphiql and pgadmin, perhaps with a default example db? That way people can just click it, run some DDL in pgadmin to get to a repro state in the DB, and then share the graphiql link – and if they wanna fiddle with plugins or whatever, they can fork, edit, and then click the same button. Would typically be free for both you and the other person. 

Downsies: Bit slow to spin up though, and annoying to fully delete an app. Of course the elephant in the room is that with pgadmin exposed, a malicious actor might be able to come along and start mining bitcoin or whatever, but frankly the blast radius seems pretty limited and you can always just delete the app.

**Comment by benjie** [comment]
Heroku’s postgres doesn’t support the CREATE ROLE command which makes that challenging too 😞

**Comment by rattrayalex** [comment]
Hmm, could it use a docker buildpack with postgres just running inside the docker image? That'd actually reduce the cost-overrun risk too, since at worst you'd use a lot of instance hours if someone kept hitting it.

**Comment by benjie** [comment]
I don't really "do" Docker; but if you fancied putting something like this together that'd be great!

**Comment by rattrayalex** [comment]
Sure, I'd like to do that! Created an issue to track (feel free to give feedback, requests, suggestions, etc there!)
